version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_olist
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_olist
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

  dev:
    build: .
    container_name: etl_dev
    working_dir: /workspace
    volumes:
      - .:/workspace
      - python_deps:/root/.local
    depends_on:
      db:
        condition: service_healthy
    command: sleep infinity
    tty: true
    stdin_open: true
    environment:
      - PREFECT_API_URL=http://host.docker.internal:4200/api   
    extra_hosts:
      - "host.docker.internal:host-gateway"
                         
  prefect-server:
    image: prefecthq/prefect:2-python3.11
    container_name: prefect_server
    restart: unless-stopped
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0
    environment:
      - PREFECT_UI_ENABLED=true
      - PREFECT_API_URL=http://0.0.0.0:4200/api
    volumes:
      - prefect_data:/root/.prefect
    depends_on:
      - dev
  
  streamlit:
    image: python:3.11-slim
    container_name: streamlit_app
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app  # Monta el directorio local con tu app Streamlit (crea este directorio con tu script main.py)
    command: bash -c "pip install --no-cache-dir -r /app/requirements.txt && streamlit run /app/main.py --server.port=8501 --server.address=0.0.0.0"
    environment:
      - POSTGRES_HOST=db  # Conecta a la DB interna
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  python_deps:
  prefect_data:
<<<<<<< HEAD

=======
  streamlit_deps:
  pgadmin_data:
>>>>>>> 6d704e1591b91948d940160547c9469ac8fc11f6
